#!/bin/bash
set -e

# Installing additional dependencies
Rscript init.R

echo "Setting up environment variables..."
TS=`date`
cat >config.R <<EOL
# DO NOT EDIT THIS FILE MANUALLY
# The contents of this file are set at runtime by
# shiny-server.sh when Docker runs.
# Generated ${TS}
APP_URL <- "${APP_URL:-}"
CLIENT_ID <- "${CLIENT_ID:-}"
CLIENT_SECRET <- "${CLIENT_SECRET:-}"
EOL

echo "Running Shiny Server..."
exec "$@"
